### ISSUE TITLE
Mappers deleted /tg/ unique content when remapping

### ISSUE THREAD

**Issue by Sarcalogo** [Carbonhell/Hippie-Rebase#106]
Someone is going to have to remap the station and actually add the relevant /tg/ features like modular computers, the stock market computer, and a bunch of shit I probably don't even know exists because when they remapped everything they just mirrored the Hippie map entirely, deleting core components of /tg/ code.

**Comment by Sarcalogo** [comment]
This makes a lot of departments basically non functional or not "updated" whoever mapped this did a really bad job.

**Comment by Sarcalogo** [comment]
I am now comparing against /tg/ code will provide a full list of things that need to be changed.

**Comment by Sarcalogo** [comment]
Bridge is missing one modular computer labeled console.

**Comment by QuarianCommando** [comment]
The idea was to rebase. Not become tg 2.0

**Comment by JamieH** [comment]
fixed by #108
