### ISSUE TITLE
Cook starts in random areas

### ISSUE THREAD

**Issue by JohnGinnane** [Carbonhell/Hippie-Rebase#66]
Just started up local server with guest account and it made me the cook. It seems to have spawned me into the atmos office:

![image](https://cloud.githubusercontent.com/assets/3355198/20774011/58f1ddc8-b74c-11e6-8fdd-a391273a78ce.png)

**Comment by JohnGinnane** [comment]
Happened again:

![image](https://cloud.githubusercontent.com/assets/3355198/20817921/7cc36c0e-b822-11e6-8d3b-632aba979366.png)

**Comment by JohnGinnane** [comment]
Seems like he'll start in random areas instead of kitchen

**Comment by yobob591** [comment]
its a feature

**Comment by Anderbergst** [comment]
is this fixed? if not i can work on this.

**Comment by Anderbergst** [comment]
I fixed this.
