### ISSUE TITLE
Lots of runtimes regarding pirate mobs

### ISSUE THREAD

**Issue by tortellinitony** [Carbonhell/Hippie-Rebase#97]
These appear to be the majority of runtime errors. They are usually along the lines of cannot execute null.something

**Comment by Pyko1** [comment]
I wonder if we should just remove the randomspaces with runtimes for now and prepare to go live and re-add later when fixed. Or actually try to get them fixed asap before going live.

Pirates and some other randomspace shit is now causing runtimes as the maps have been re-pathed so they can be loaded by random space generator.

**Comment by KayeArray** [comment]
Seriously fuck these stupid useless cunts always flooding my console with runtimes, delet.

**Comment by Pyko1** [comment]
quite a few maps have pirates and syndies tho

**Comment by tortellinitony** [comment]
Looks like it was fixed.
